/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.itsm.deep;import cn.zhuatech.itsm.common.ApiResponse;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/admin/itsm-ops") @PreAuthorize("hasRole('ADMIN')") public class DeepItsmAdminController{private final DeepItsmService s;/**
                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                               */
public DeepItsmAdminController(DeepItsmService x){s=x;}/**
                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                      */
@PostMapping("/cis")ApiResponse<?> ci(@RequestBody DeepItsmService.CiInput x){return ApiResponse.ok(s.createCi(x));}/**
                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                          */
@PostMapping("/cis/{id}/activate")ApiResponse<?> activate(@PathVariable Long id){return ApiResponse.ok(s.activateCi(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/problems/{id}/close")ApiResponse<?> problem(@PathVariable Long id){return ApiResponse.ok(s.closeProblem(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
@PostMapping("/changes/{id}/approve")ApiResponse<?> approve(@PathVariable Long id,@RequestBody DeepItsmService.ApprovalInput x){return ApiResponse.ok(s.approveChange(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@PostMapping("/changes/{id}/implement")ApiResponse<?> implement(@PathVariable Long id,@RequestBody DeepItsmService.EvidenceInput x){return ApiResponse.ok(s.implement(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/changes/{id}/close")ApiResponse<?> close(@PathVariable Long id){return ApiResponse.ok(s.closeChange(id));}}
