/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.itsm.deep;import jakarta.persistence.*;import org.springframework.http.*;import org.springframework.stereotype.*;import org.springframework.transaction.annotation.*;import org.springframework.web.server.*;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true) public class DeepItsmService{private final EntityManager em;/**
                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                    */
public DeepItsmService(EntityManager e){em=e;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public CiView createCi(CiInput x){var c=new ManagedCI(x.ciCode(),x.name(),x.type(),x.criticality(),x.owner());em.persist(c);audit("CREATE_CI",x.ciCode(),x.name());return view(c);}/**
                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                    */
@Transactional public CiView activateCi(Long id){var c=ci(id);if(!"DRAFT".equals(c.status))throw conflict("配置项状态不可启用");c.status="ACTIVE";return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public IncidentView incident(IncidentInput x){var c=ci(x.ciId());if(!"ACTIVE".equals(c.status))throw conflict("配置项未启用");if(!Set.of("P1","P2","P3","P4").contains(x.priority()))throw bad("优先级无效");int h=switch(x.priority()){case"P1"->1;case"P2"->4;case"P3"->12;default->24;};var i=new ItsmIncident(x.incidentNo(),c.id,x.priority(),x.summary(),h);em.persist(i);audit("CREATE_INCIDENT",i.incidentNo,x.priority());return view(i);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public IncidentView assign(Long id,AssignInput x){var i=incident(id);if(!"OPEN".equals(i.status))throw conflict("事件状态不可分派");i.assignee=x.assignee();i.status="ASSIGNED";return view(i);}/**
                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                         */
@Transactional public IncidentView resolve(Long id,ResolveInput x){var i=incident(id);if(!"ASSIGNED".equals(i.status))throw conflict("仅已分派事件可解决");i.resolution=x.resolution();i.status="RESOLVED";i.resolvedAt=LocalDateTime.now();audit("RESOLVE_INCIDENT",i.incidentNo,x.resolution());return view(i);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@Transactional public IncidentView closeIncident(Long id){var i=incident(id);if(!"RESOLVED".equals(i.status))throw conflict("事件须先解决再关闭");i.status="CLOSED";return view(i);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public ProblemView problem(ProblemInput x){var i=incident(x.incidentId());if(!Set.of("RESOLVED","CLOSED").contains(i.status))throw conflict("问题管理需基于已解决事件");var p=new ItsmProblem(x.problemNo(),i.id,x.rootCause(),x.knownError(),x.workaround());em.persist(p);return view(p);}/**
                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                 */
@Transactional public ProblemView closeProblem(Long id){var p=problem(id);if(p.rootCause==null||p.rootCause.isBlank()||p.workaround==null||p.workaround.isBlank())throw conflict("根因与规避方案未完善");p.status="CLOSED";return view(p);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public ChangeView change(ChangeInput x){var c=ci(x.ciId());if(!"ACTIVE".equals(c.status))throw conflict("配置项未启用");int risk=Math.min(100,x.impact()*x.probability()*4+("EMERGENCY".equals(x.changeType())?20:0));var ch=new ItsmChange(x.changeNo(),c.id,x.changeType(),risk,x.description(),x.rollbackPlan());em.persist(ch);return view(ch);}/**
                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                               */
@Transactional public ChangeView submitChange(Long id){var c=change(id);if(!"DRAFT".equals(c.status)||c.rollbackPlan==null||c.rollbackPlan.isBlank())throw conflict("变更缺少回退方案或状态无效");c.status="CAB_REVIEW";return view(c);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@Transactional public ChangeView approveChange(Long id,ApprovalInput x){var c=change(id);if(!"CAB_REVIEW".equals(c.status))throw conflict("变更不在CAB评审状态");c.status=x.approved()?"APPROVED":"REJECTED";return view(c);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@Transactional public ChangeView implement(Long id,EvidenceInput x){var c=change(id);if(!"APPROVED".equals(c.status))throw conflict("仅批准变更可以实施");if(x.evidenceHash()==null||x.evidenceHash().length()<16)throw bad("实施证据摘要不足");c.evidenceHash=x.evidenceHash();c.status="IMPLEMENTED";audit("IMPLEMENT_CHANGE",c.changeNo,x.evidenceHash());return view(c);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@Transactional public ChangeView closeChange(Long id){var c=change(id);if(!"IMPLEMENTED".equals(c.status))throw conflict("变更尚未实施");c.status="CLOSED";return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public Workspace workspace(){return new Workspace(cis(),incidents(),problems(),changes());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private ManagedCI ci(Long id){var x=em.find(ManagedCI.class,id);if(x==null)throw missing("配置项不存在");return x;}/**
                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                               */
private ItsmIncident incident(Long id){var x=em.find(ItsmIncident.class,id);if(x==null)throw missing("事件不存在");return x;}/**
                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                       */
private ItsmProblem problem(Long id){var x=em.find(ItsmProblem.class,id);if(x==null)throw missing("问题不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                            */
private ItsmChange change(Long id){var x=em.find(ItsmChange.class,id);if(x==null)throw missing("变更不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
private void audit(String a,String n,String d){em.persist(new ItsmAudit(a,n,d));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<CiView>cis(){return em.createQuery("select c from ManagedCI c order by c.id desc",ManagedCI.class).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                     */
private List<IncidentView>incidents(){return em.createQuery("select i from ItsmIncident i order by i.id desc",ItsmIncident.class).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                          */
private List<ProblemView>problems(){return em.createQuery("select p from ItsmProblem p order by p.id desc",ItsmProblem.class).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private List<ChangeView>changes(){return em.createQuery("select c from ItsmChange c order by c.id desc",ItsmChange.class).getResultList().stream().map(this::view).toList();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private CiView view(ManagedCI c){return new CiView(c.id,c.ciCode,c.name,c.type,c.criticality,c.owner,c.status,c.lockVersion);}/**
                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                */
private IncidentView view(ItsmIncident i){return new IncidentView(i.id,i.incidentNo,i.ciId,i.priority,i.summary,i.status,i.assignee,i.dueAt,i.major,i.resolution,i.lockVersion);}/**
                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                 */
private ProblemView view(ItsmProblem p){return new ProblemView(p.id,p.problemNo,p.incidentId,p.rootCause,p.knownError,p.workaround,p.status,p.lockVersion);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
private ChangeView view(ItsmChange c){return new ChangeView(c.id,c.changeNo,c.ciId,c.changeType,c.riskScore,c.description,c.rollbackPlan,c.status,c.evidenceHash,c.lockVersion);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                              */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                            */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record CiInput(String ciCode,String name,String type,String criticality,String owner){}/**
                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                */
public record IncidentInput(String incidentNo,Long ciId,String priority,String summary){}/**
                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                         */
public record AssignInput(String assignee){}/**
                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                     */
public record ResolveInput(String resolution){}/**
                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                    */
public record ProblemInput(String problemNo,Long incidentId,String rootCause,String knownError,String workaround){}/**
                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                       */
public record ChangeInput(String changeNo,Long ciId,String changeType,int impact,int probability,String description,String rollbackPlan){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
public record ApprovalInput(boolean approved){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public record EvidenceInput(String evidenceHash){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
public record CiView(Long id,String ciCode,String name,String type,String criticality,String owner,String status,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
public record IncidentView(Long id,String incidentNo,Long ciId,String priority,String summary,String status,String assignee,LocalDateTime dueAt,boolean major,String resolution,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
public record ProblemView(Long id,String problemNo,Long incidentId,String rootCause,String knownError,String workaround,String status,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public record ChangeView(Long id,String changeNo,Long ciId,String changeType,int riskScore,String description,String rollbackPlan,String status,String evidenceHash,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
public record Workspace(List<CiView>configurationItems,List<IncidentView>incidents,List<ProblemView>problems,List<ChangeView>changes){}
}
