/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.itsm.deep;import cn.zhuatech.itsm.common.ApiResponse;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/itsm-ops") public class DeepItsmController{private final DeepItsmService s;/**
                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                  */
public DeepItsmController(DeepItsmService x){s=x;}/**
                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                    */
@GetMapping("/workspace")ApiResponse<?> workspace(){return ApiResponse.ok(s.workspace());}/**
                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                              */
@PostMapping("/incidents")ApiResponse<?> incident(@RequestBody DeepItsmService.IncidentInput x){return ApiResponse.ok(s.incident(x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/incidents/{id}/assign")ApiResponse<?> assign(@PathVariable Long id,@RequestBody DeepItsmService.AssignInput x){return ApiResponse.ok(s.assign(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
@PostMapping("/incidents/{id}/resolve")ApiResponse<?> resolve(@PathVariable Long id,@RequestBody DeepItsmService.ResolveInput x){return ApiResponse.ok(s.resolve(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/incidents/{id}/close")ApiResponse<?> close(@PathVariable Long id){return ApiResponse.ok(s.closeIncident(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@PostMapping("/problems")ApiResponse<?> problem(@RequestBody DeepItsmService.ProblemInput x){return ApiResponse.ok(s.problem(x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
@PostMapping("/changes")ApiResponse<?> change(@RequestBody DeepItsmService.ChangeInput x){return ApiResponse.ok(s.change(x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@PostMapping("/changes/{id}/submit")ApiResponse<?> submit(@PathVariable Long id){return ApiResponse.ok(s.submitChange(id));}}
