/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.itsm;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class DeepItsmOpsTests{@Autowired MockMvc mvc;String token;/**
                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                  */
@BeforeEach void auth()throws Exception{String j=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"admin\",\"password\":\"ZhuaTech@2026\"}")).andReturn().getResponse().getContentAsString();var m=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(j);Assertions.assertTrue(m.find());token=m.group(1);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void incidentProblemAndChangeFormControlledLoops()throws Exception{long ci=ci("APP-A");long in=id(call("/api/itsm-ops/incidents","{\"incidentNo\":\"INC-A\",\"ciId\":"+ci+",\"priority\":\"P1\",\"summary\":\"核心应用不可用\"}").andExpect(jsonPath("$.data.major").value(true)).andReturn());call("/api/itsm-ops/incidents/"+in+"/assign","{\"assignee\":\"engineer1\"}");call("/api/itsm-ops/incidents/"+in+"/resolve","{\"resolution\":\"重启故障节点并切换流量\"}");call("/api/itsm-ops/incidents/"+in+"/close","{}");long p=id(call("/api/itsm-ops/problems","{\"problemNo\":\"PRB-A\",\"incidentId\":"+in+",\"rootCause\":\"连接池耗尽\",\"knownError\":\"高峰连接泄露\",\"workaround\":\"定时回收并限流\"}").andReturn());admin("/api/admin/itsm-ops/problems/"+p+"/close","{}");long c=id(call("/api/itsm-ops/changes","{\"changeNo\":\"CHG-A\",\"ciId\":"+ci+",\"changeType\":\"NORMAL\",\"impact\":3,\"probability\":2,\"description\":\"升级连接池组件\",\"rollbackPlan\":\"恢复上一镜像\"}").andReturn());call("/api/itsm-ops/changes/"+c+"/submit","{}");admin("/api/admin/itsm-ops/changes/"+c+"/approve","{\"approved\":true}");admin("/api/admin/itsm-ops/changes/"+c+"/implement","{\"evidenceHash\":\"abcdef0123456789abcdef\"}");admin("/api/admin/itsm-ops/changes/"+c+"/close","{}").andExpect(jsonPath("$.data.status").value("CLOSED"));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void unassignedIncidentCannotResolve()throws Exception{long ci=ci("APP-B");long in=id(call("/api/itsm-ops/incidents","{\"incidentNo\":\"INC-B\",\"ciId\":"+ci+",\"priority\":\"P3\",\"summary\":\"一般告警\"}").andReturn());call("/api/itsm-ops/incidents/"+in+"/resolve","{\"resolution\":\"跳过分派\"}").andExpect(status().isConflict());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void changeRequiresRollbackAndEvidence()throws Exception{long ci=ci("APP-C");long c=id(call("/api/itsm-ops/changes","{\"changeNo\":\"CHG-C\",\"ciId\":"+ci+",\"changeType\":\"NORMAL\",\"impact\":2,\"probability\":2,\"description\":\"配置修改\",\"rollbackPlan\":\"\"}").andReturn());call("/api/itsm-ops/changes/"+c+"/submit","{}").andExpect(status().isConflict());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 long ci(String c)throws Exception{long id=id(admin("/api/admin/itsm-ops/cis","{\"ciCode\":\""+c+"\",\"name\":\"核心应用\",\"type\":\"APPLICATION\",\"criticality\":\"HIGH\",\"owner\":\"平台部\"}").andReturn());admin("/api/admin/itsm-ops/cis/"+id+"/activate","{}");return id;}/**
                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                             */
ResultActions call(String u,String b)throws Exception{return mvc.perform(post(u).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
ResultActions admin(String u,String b)throws Exception{return call(u,b);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
long id(MvcResult r)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}}
